### PR TITLE
Feature/updating fitting

### PR DESCRIPTION
**Pull request by RafaelPalomar**

### CODE REVIEW

**Comment by RafaelPalomar** [comment]
@RuoyanMeng, @dalbenzioG, could you have a review on this PR, which it is your latest additions without git conflicts?

**Review by RuoyanMeng — COMMENTED** [review]
There is no problem from my side, @dalbenzioG Could you take a look at liver.py? I think we have tested everything previously but it's good to double-check it.

**Comment by dalbenzioG** [comment]
> @RuoyanMeng, @dalbenzioG, could you have a review on this PR, which it is your latest additions without git conflicts?

I have just checked and also all features for the resection planning work fine :+1:

**Review by RuoyanMeng — APPROVED** [review]

**Comment by RuoyanMeng** [comment]
@RafaelPalomar We have reviewed the code, and there is no problem. Should we do Rebase and merge?

**Pull request merged**
