### PR TITLE
ENH: Fix circleci configuration file

### PR DESCRIPTION
**Pull request by RafaelPalomar**
- Migration of the the repository to Slicer-Liver requires the
modification of the circleci configuration file. This does that change.

### CODE REVIEW

**Comment by olevs** [comment]
@RafaelPalomar It Seems like you have to set up Slicer-Liver as a project on CircleCI, in order to get the tests running

**Comment by RafaelPalomar** [comment]
@olevs I've created the project in CircleCi. Could you check it works properly?

**Comment by RafaelPalomar** [comment]
It seems that the build fails. I wonder if this is due to the .circleci being included in the commit or if it is anything else. @olevs, any ideas?

**Comment by olevs** [comment]
Strange. It's either that or it's having problems pulling from your fork?

**Pull request merged**
