### PR TITLE
Implementation of Liver vascular segments annotation and calculation

### PR DESCRIPTION
**Pull request by olevs**
The first version of the Liver vascular segment calculation is finished and ready to merge.

### CODE REVIEW

**Comment by olevs** [comment]
CircleCI tests fails because it cannot find the ExtractCenterline module from the SlicerVMTK plugin.

**Comment by olevs** [comment]
After fixing #132, the tests are now running correctly on CircleCI, and the branch can be merged

**Review by RafaelPalomar — COMMENTED** [review]
Good work!

Due to a couple of changes I have added on this, this is superseded by alive-research/slicer-liver#133:

  - Some adjustments to UI to make it more compact.
  - Remove the LiverSegments UI from the Liver module
  - Add license heading to LiverSegments.py
  - Add mouse working icon when computing the centerlines

**Comment by RafaelPalomar** [comment]
This is superseded by https://github.com/ALive-research/Slicer-Liver/pull/133

**Pull request closed without merging**
