### PR TITLE
ENH: Arbitrary Resection Volumetry Calculation

### PR DESCRIPTION
**Pull request by RuoyanMeng**
#236, #238 solved

### CODE REVIEW

**Comment by RuoyanMeng** [comment]
Hi @RafaelPalomar, I update the UI and functionality: 

1. Now users can calculate ROI volume for any case, with or without resection, using either vascular segments, single resection or multiple resections. 
2. The UI is more intuitive, with basic functions for simple resection volumetry, Use-All-Resections and Vascular-segments as advanced parameters.

Could you try it and give me some feedback?

**Comment by RuoyanMeng** [comment]
The latest commit contains big changes in the code structure and UI. 

- Move the code from live.py and liverResectionLogic to an independent module.
- New design for segmentation and its segments choice, now you can do multi-selection on whatever segments you are interested in.
- Including "Resection" in volume calculation is an advanced feature for volume calculation now. In this version, only "single resection" or "All resection" options are there, will add multi-selection in the future.

**Comment by RafaelPalomar** [comment]
@RuoyanMeng, here there is an example of use of normalized device coordinates for a given actor. (I haved not tried) but this should help you representing your actors in terms of final coordinates in the range 0-1, so you easily scale the resectogram. Let me know when this is ready for review.

https://examples.vtk.org/site/Cxx/Annotation/MultiLineText/

**Comment by RuoyanMeng** [comment]
#226 solved

**Review by RafaelPalomar — APPROVED** [review]

**Pull request merged**
