### PR TITLE
ENH: Adding distance calculation logic + UI

### PR DESCRIPTION
**Pull request by RafaelPalomar**

### CODE REVIEW

**Comment by RafaelPalomar** [comment]
@olevs, any idea why some PRs are not tested?

**Comment by olevs** [comment]
Strange. The Slicer-Liver project seems to be set up correctly on CircleCI. Maybe it have issues with forks?

**Comment by olevs** [comment]
@RafaelPalomar Have you removed all of the old GUI?
I also seems like the Qt connects in your .ui file don't work correctly. I get Qt errors on the command line (but not in the Python window in Slicer)

**Comment by RafaelPalomar** [comment]
@olevs I removed the old GUI that will be superseded by the new GUI in Alive-research/Slicer-Liver#34. That GUI has 3 parts, the first one is integrated in this commit; I'm working on the second one (hopefully it will be ready tomorrow); and the third one is related to the vascular territories. All of them are independent.

> I also seems like the Qt connects in your .ui file don't work correctly. I get Qt errors on the command line (but not in the Python window in Slicer)

Yes, I was developing on the basis of Slicer/Slicer#6129 which has not been merged. I reverted to Slicer-master and made the changes in Alive-research/Slicer-Liver accordingly. Now it should work. 

@olevs Any idea why the tests are not run in this PR?

**Comment by olevs** [comment]
@RafaelPalomar I found a "Build forked pull requests" setting that is off by default. Hopefully it will work better now that I have turned it on

**Comment by RafaelPalomar** [comment]
> @RafaelPalomar I found a "Build forked pull requests" setting that is off by default. Hopefully it will work better now that I have turned it on

Good! It seems it works!

**Pull request merged**
