### PR TITLE
Feature/joss paper

### PR DESCRIPTION
**Pull request by RafaelPalomar**
This is a revised draft for the JOSS submission. 

@everyone review the draft and leave your comments as a review.
@olevs could you check the pdf artifact is properly configured and set for this branch/PR? at least as a branch I could not get it to build.

### CODE REVIEW

**Comment by olevs** [comment]
@RafaelPalomar I fixed a bug in the .yml file, but it won't run. You probably have to go to Settings->Actions->General and select "Allow all actions and reusable workflows"

**Comment by RafaelPalomar** [comment]
@olevs, @gatangen, @dalbenzioG, @RuoyanMeng thanks to Ole V., now we have the generation of the pdf paper in a workflow (go to the "Actions" menu, look for the last build and see the built artifact "paper.zip").

@dalbenzioG you don't seem to have an ORCID? You should probably register and add your ORCID ID to the paper.
@RuoyanMeng your orcid may not be correct or may not be public. When I click on the ORCID link rendered in the pdf I can't see any content (please, check).

@dalbenzioG, @RuoyanMeng, please replace the segments figure by one figure with proper Couinaud segments. The one provided only considers one segment and the rest of the parenchyma.

@everyone, please, review the pdf manuscript and approve the github PR review so I know you are ok with the draft

**Comment by dalbenzioG** [comment]
> @olevs, @gatangen, @dalbenzioG, @RuoyanMeng thanks to Ole V., now we have the generation of the pdf paper in a workflow (go to the "Actions" menu, look for the last build and see the built artifact "paper.zip").
> 
> @dalbenzioG you don't seem to have an ORCID? You should probably register and add your ORCID ID to the paper. @RuoyanMeng your orcid may not be correct or may not be public. When I click on the ORCID link rendered in the pdf I can't see any content (please, check).
> 
> @dalbenzioG, @RuoyanMeng, please replace the segments figure by one figure with proper Couinaud segments. The one provided only considers one segment and the rest of the parenchyma.
> 
> @everyone, please, review the pdf manuscript and approve the github PR review so I know you are ok with the draft

Thank you @olevs! 
@RafaelPalomar I will add my ORCID and a figure with proper Couinaud segments ASAP.

**Comment by RuoyanMeng** [comment]
> @olevs, @gatangen, @dalbenzioG, @RuoyanMeng thanks to Ole V., now we have the generation of the pdf paper in a workflow (go to the "Actions" menu, look for the last build and see the built artifact "paper.zip").
> 
> @dalbenzioG you don't seem to have an ORCID? You should probably register and add your ORCID ID to the paper. @RuoyanMeng your orcid may not be correct or may not be public. When I click on the ORCID link rendered in the pdf I can't see any content (please, check).
> 
> @dalbenzioG, @RuoyanMeng, please replace the segments figure by one figure with proper Couinaud segments. The one provided only considers one segment and the rest of the parenchyma.
> 
> @everyone, please, review the pdf manuscript and approve the github PR review so I know you are ok with the draft

Thanks @RafaelPalomar and @olevs.
I have fixed the ORCID issue from orcid website.

**Review by dalbenzioG — APPROVED** [review]

**Comment by RuoyanMeng** [comment]
@dalbenzioG Could you try to take back the commit that removed {width= 100%}, it's used for indicating the width of resectogram pic, it won't show in build pdf :-)

**Comment by olevs** [comment]
@dalbenzioG I did some changes to your last commits: Use only one ref to fig 4 in the text, and moved the Bismuth 1982 ref (otherwise it may have looked like figure 4 was from the Bismuth paper)
Please check if you agree with my changes

**Comment by dalbenzioG** [comment]
> @dalbenzioG I did some changes to your last commits: Use only one ref to fig 4 in the text, and moved the Bismuth 1982 ref (otherwise it may have looked like figure 4 was from the Bismuth paper) Please check if you agree with my changes

Thank you, @olevs. You are right!

**Comment by dalbenzioG** [comment]
> @dalbenzioG Could you try to take back the commit that removed {width= 100%}, it's used for indicating the width of resectogram pic, it won't show in build pdf :-)

Thank you,@RuoyanMeng, for spotting the error! I have reverted the changes.

**Review by olevs — APPROVED** [review]

**Review by gatangen — APPROVED** [review]
Regarding license we state in the source code files : "Distributed under the OSI-approved BSD 3-Clause License." Is this identical to the MIT license referenced in the paper text?

**Review by RuoyanMeng — APPROVED** [review]

**Comment by RafaelPalomar** [comment]
I'll proceed with the submission (most likely next week)

**Pull request merged**
