### PR TITLE
ENH: Add templates for issues

### PR DESCRIPTION
**Pull request by RafaelPalomar**
This closes ALive-research/Slicer-Liver#26 and ALive-research/Slicer-Liver#27

### CODE REVIEW

**Comment by RafaelPalomar** [comment]
What do you guys think about this issue templates?

**Review by gatangen — COMMENTED** [review]
Suggest to add a label for Slicer version in the bug report. 
Maybe add a separate template for "Improvement  Request" ?

**Review by jpdefrutosSINTEF — APPROVED** [review]
Looks good! Together with Geir Arne's suggestion, I'd also add a label for the Liver extension version in use. Perhaps suggest the user to provide a screen recording? or data (if used, and if possible) to reproduce the error? (in addition to the steps needed to trigger the error).

**Comment by olevs** [comment]
This is great. Program versions is nice to have. Perhaps also suggest that the user includes call stack if available? Like in the help text under "Additional context".

**Review by olevs — APPROVED** [review]

**Comment by RafaelPalomar** [comment]
> Suggest to add a label for Slicer version in the bug report. Maybe add a separate template for "Improvement Request" ?

@gatangen, isn't that already considered in "feature request", or "improvement request" could be something else?

**Comment by RafaelPalomar** [comment]
> Looks good! Together with Geir Arne's suggestion, I'd also add a label for the Liver extension version in use. Perhaps suggest the user to provide a screen recording? or data (if used, and if possible) to reproduce the error? (in addition to the steps needed to trigger the error).

This we will have to set it up manually ourselves since we are using milestones instead of labels for the version tracking. But definitely we will assign issues to version. The user can specify which version they found the error in.

**Comment by gatangen** [comment]
@RafaelPalomar , I understrand "Feature Request" as a request for new functionality or new characteristics of the system while "Improvement" is more a suggestion for improvement of existing functionality or general improvement of the system. What do you think?

**Comment by RafaelPalomar** [comment]
> @RafaelPalomar , I understrand "Feature Request" as a request for new functionality or new characteristics of the system while "Improvement" is more a suggestion for improvement of existing functionality or general improvement of the system. What do you think?

I see. It makes sense. I have added a new template "Improvement request".

**Comment by jpdefrutosSINTEF** [comment]
After using the bugs template, perhaps I would remove the label "name" and move "title" to the top. I feel these two refer to somewhat the same thing. Something like this:

---
title:
about: 
labels: bug
assignees: ''

---

**Comment by RafaelPalomar** [comment]
> After using the bugs template, perhaps I would remove the label "name" and move "title" to the top. I feel these two refer to somewhat the same thing. Something like this:
> 
> title: about: labels: bug assignees: ''

These are `metadata`. They are not part of the template per se and I think cannot be removed :)

**Comment by jpdefrutosSINTEF** [comment]
> > After using the bugs template, perhaps I would remove the label "name" and move "title" to the top. I feel these two refer to somewhat the same thing. Something like this:
> > title: about: labels: bug assignees: ''
> 
> These are `metadata`. They are not part of the template per se and I think cannot be removed :)

ups!
Then forget what I said ^^

**Pull request merged**
