### PR TITLE
Bug/multiple vascular territories #249

### PR DESCRIPTION
**Pull request by gatangen**

### CODE REVIEW

**Comment by RafaelPalomar** [comment]
@gatangen, I see some movements in this PR, is it ready for review?

**Comment by gatangen** [comment]
Hi Rafael,

I will write some comments about the changes and have a final commit I’m testing now. But, should be ready for review Monday morning. Finally 😊

Geir Arne


From: Rafael Palomar ***@***.***>
Date: Friday, 24 November 2023 at 14:37
To: ALive-research/Slicer-Liver ***@***.***>
Cc: Geir Arne Tangen ***@***.***>, Mention ***@***.***>
Subject: Re: [ALive-research/Slicer-Liver] Bug/multiple vascular territories #249 (PR #256)

@gatangen<https://github.com/gatangen>, I see some movements in this PR, is it ready for review?

**Comment by gatangen** [comment]
Findings during review: 
1.  When switching between already generated Vascular Territory Segmentations, the Vessel Points list is not correctly updated.
2. We get multiple instances of the colour table SlicerLiverColorMap.

**Comment by gatangen** [comment]
(1) fixed in commit 68c99fdb34b79978c709b117d25722840928e768.
(2) caused by faulty test setup.

**Comment by olevs** [comment]
Trying to load previous data seems to fail, and cause Slicer to crash:
vtkMRMLVolumeArchetypeStorageNode::ReadDataInternal: Cannot read file as a volume of type Volume [fullName = /home/olevs/Documents/Joss_Slicer_example/Segment_1_Territory_1_hepatic.mrk.json]: FileFormatError. Number of files listed in the node = 0. File reader says it was able to read 0 files. File reader used the archetype file name of /home/olevs/Documents/Joss_Slicer_example/Segment_1_Territory_1_hepatic.mrk.json [].

Skipping the loading of Segment_1_Territory_1_hepatic.mrk.json and ...Scene.mrml seems to work

**Comment by olevs** [comment]
When restarting Slicer and loading previous data all GUI fields in "Liver Vascular Territories" are disabled, even if the previous "Vascular Territory Segmentation" is selected. A workaround is to create a new Vascular Territory Segmentation and switch back to the first.

**Comment by gatangen** [comment]
> Issues when loading previous session:
> 
> * When restarting Slicer and loading previous data all GUI fields in "Liver Vascular Territories" are disabled, even if the previous "Vascular Territory Segmentation" is selected. A workaround is to create a new Vascular Territory Segmentation and switch back to the first.
>   
>   * The "Show 3D" button will still be disabled, and another segmentation will have to be selected to enable this
> * Trying to calculate vascular territory segmentation on previous data don't seem to work
> * The data failing to load in the previous comment (Segment_1_Territory_1_hepatic.mrk.json) got type "Volume" instead of "Markups", and it is not possible to change type on load

Yes, storing of information in Parameter node, and updating of GUI from Parameter node needs to be implemented. I can have a look at it.

**Comment by gatangen** [comment]
Fixed in commit 3e9cb5b51c70a2f091e81ed818f6a79021fa2c66.
Not able to recreate the "data failing to load" situation. Is this still an issue @olevs ?

**Review by olevs — APPROVED** [review]

**Pull request merged**
