### PR TITLE
Feature/updating resectograms

### PR DESCRIPTION
**Pull request by RafaelPalomar**

### CODE REVIEW

**Comment by RuoyanMeng** [comment]
There are so many differences in UI and liver.py file, so I decided to manually solve the conflicts and start a new pull request

**Comment by olevs** [comment]
@RafaelPalomar For the CircleCI tests to pass, the latest changes from develop needs to be merged in. Like this: https://github.com/ALive-research/Slicer-Liver/compare/feature/updating_resectograms...develop

**Comment by RafaelPalomar** [comment]
> There are so many differences in UI and liver.py file, so I decided to manually solve the conflicts and start a new pull request

Is this PR not working?

**Comment by RafaelPalomar** [comment]
> @RafaelPalomar For the CircleCI tests to pass, the latest changes from develop needs to be merged in. Like this: [feature/updating_resectograms...develop](https://github.com/ALive-research/Slicer-Liver/compare/feature/updating_resectograms...develop)

@olevs , yes, I did rebase to the latest `develop` branch and now the tests are passed. Thanks for pointing it out.

**Comment by RuoyanMeng** [comment]
I saw the CI test is not passed and the comparison of this branch and my
local branch contains many differences especially in the UI and liver.py.
And my local comparison tool seems give messy differences make them
unreadable. So I start a clean one only compare my branch and develop to
make things easier for me😀

**Comment by dalbenzioG** [comment]
After conducting tests on the Bézier fitting functionality, I can confirm its successful implementation within this PR. I will also be reviewing the PR submitted by Meng today. However, given that I only coded in python, I do not expect encountering any significant complications. I am also anticipating here that I have more features (improved parametrization and fitting a Béziersurface from a MarkupClosedCurve) that could be add once the conflicts between my code and Meng's one are solved.

**Comment by RafaelPalomar** [comment]
This is superseded by ALive-research/Slicer-Liver#204 due to merge conflicts

**Pull request closed without merging**
